name: run-e2e

on:
  push:
    branches:
      - go/playwright-e2e

jobs:
  test-e2e:
    name: test-e2e
    runs-on: ubuntu-latest
    services:
      mailhog:
        image: mailhog/mailhog:latest
        ports:
          - "8025:8025"
          - "1025:1025"
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: fider_ci
          POSTGRES_PASSWORD: fider_ci_pw
          POSTGRES_DB: fider_ci
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      # - run: docker build -t getfider/fider .
      - run: |
          docker run \
            -p 3000:3000 \
            --env MYVAR2=foo \
            --env DATABASE_URL=postgres://fider_ci:fider_ci_pw@postgres:5432/fider_ci?sslmode=disable \
            --env JWT_SECRET=not_so_secret \
            --env HOST_MODE=multi \
            --env HOST_DOMAIN=dev.fider.io \
            --env SSL_CERT=dev-fider-io.crt \
            --env SSL_CERT_KEY=dev-fider-io.key \
            --env EMAIL_NOREPLY=noreply@fider.io \
            --env EMAIL_SMTP_HOST=mailhog \
            --env EMAIL_SMTP_PORT=1025 \
            -d --network "${{ job.container.network }}" \
            -v "$PWD"/etc:/app/etc \
            getfider/fider:main
      - run: npm ci
      - run: npx playwright install-deps
      - run: make test-e2e